# Generated by Django 3.2.16 on 2023-01-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('time_of_day', models.CharField(max_length=50)),
                ('day_1_2day', models.CharField(max_length=500)),
                ('day_2_2day', models.CharField(max_length=500)),
            ],
        ),
    ]
