# Generated by Django 3.2.16 on 2023-01-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_itinerary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='day_1_2day',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='day_2_2day',
            field=models.CharField(max_length=200),
        ),
    ]
