# Generated by Django 3.2.16 on 2023-01-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20230118_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='day_1_2day',
            new_name='day_1',
        ),
        migrations.RenameField(
            model_name='itinerary',
            old_name='day_2_2day',
            new_name='day_2',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='identifier',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
