# Generated by Django 3.2.16 on 2023-01-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230118_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='activity_type',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='identifier',
            field=models.CharField(max_length=5),
        ),
    ]
