# Generated by Django 3.2.16 on 2023-01-20 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20230120_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itinerary',
            old_name='length',
            new_name='days',
        ),
    ]
