# Generated by Django 3.2.16 on 2023-01-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_length_itinerary_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='identifier',
            field=models.CharField(default='none', max_length=5),
            preserve_default=False,
        ),
    ]
