# Generated by Django 3.2.16 on 2023-01-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_itinerary_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='city',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='day_1',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='day_2',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='day_3',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='day_4',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='time_of_day',
        ),
    ]
