# Generated by Django 3.2.16 on 2023-01-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20230120_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asdf', models.CharField(max_length=3)),
                ('agfds', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
