# Generated by Django 3.2.16 on 2023-01-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20230120_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
